/**
 * Icons.tsx — 应用图标集（改用 lucide-react 渲染）。
 *
 * 保留既有 `<Icon name="save" size={16} />` 调用约定不变；内部把每个 name 映射到一个
 * lucide-react 图标组件。lucide 默认 `stroke="currentColor"` / `fill="none"` / 圆角端点，
 * 与原自绘 SVG 一致；线宽沿用原先的 1.6（lucide 默认 2），以保持视觉权重接近。
 * `fill` 用于实心状态点（如脏标记圆点），令 lucide 描边图标改为实心填充。
 */
import {
  FilePlus,
  FileText,
  FileArchive,
  FileAudio,
  FileCode,
  FileImage,
  FileJson,
  FileQuestionMark,
  FileSpreadsheet,
  FileType,
  FileVideo,
  FolderOpen,
  FolderTree,
  Save,
  SaveAll,
  Folder,
  Clock,
  CalendarDays,
  Upload,
  PanelLeft,
  PanelRight,
  List,
  Terminal,
  CircleHelp,
  Settings,
  Sun,
  Moon,
  WandSparkles,
  Code,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  X,
  MoveHorizontal,
  SquarePen,
  Columns2,
  Eye,
  FilePen,
  Crosshair,
  Monitor,
  SpellCheck,
  Search,
  Plus,
  BookOpen,
  ExternalLink,
  RotateCw,
  Check,
  Star,
  File,
  Delete,
  Circle,
  Info,
  TriangleAlert,
  Play,
  Square,
  Brain,
  Wrench,
  GitCommitHorizontal,
  MessageSquare,
  NotebookPen,
  Cloud,
  Plug,
  PenLine,
  Trash2,
  Globe,
  Package,
  Key,
  Lock,
  Clipboard,
  Image,
  Sparkles,
  Eraser,
  FolderPlus,
  Pencil,
  Heart,
  ArrowRight,
  Presentation,
  Hash,
  ListChecks,
  Bell,
  AlarmClock,
  type LucideIcon,
} from 'lucide-react';

// name → lucide 组件。命名沿用工具栏/视图既有 key，新增 key 时在此登记即可。
const ICONS: Record<string, LucideIcon> = {
  // 工具栏 / 视图（原 <Icon> 图标集）
  new: FilePlus,
  'new-text': FileText,
  open: FolderOpen,
  save: Save,
  'save-as': SaveAll,
  folder: Folder,
  recent: Clock,
  calendar: CalendarDays,
  export: Upload,
  sidebar: PanelLeft,
  'sidebar-right': PanelRight,
  outline: List,
  palette: Terminal,
  help: CircleHelp,
  settings: Settings,
  'theme-light': Sun,
  'theme-dark': Moon,
  live: WandSparkles,
  source: Code,
  'chevron-down': ChevronDown,
  close: X,
  'fit-width': MoveHorizontal,
  'view-edit': SquarePen,
  'view-split': Columns2,
  'view-preview': Eye,
  'view-live': FilePen,
  focus: Crosshair,
  typewriter: Monitor,
  spellcheck: SpellCheck,
  search: Search,
  insert: Plus,
  'view-reading': BookOpen,
  external: ExternalLink,
  // 各组件原 Unicode 字形 → lucide（折叠箭头 / 关闭 / 勾选 / 状态等）
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  refresh: RotateCw,
  check: Check,
  star: Star,
  file: File,
  clear: Delete,
  circle: Circle,
  info: Info,
  warning: TriangleAlert,
  // Trace step 类型图标（原 emoji）
  play: Play,
  stop: Square,
  brain: Brain,
  tool: Wrench,
  'git-commit': GitCommitHorizontal,
  prompt: MessageSquare,
  note: NotebookPen,
  // 各组件原 emoji 图标 → lucide（设置分类导航 / 文件树右键菜单 / 对话框 / 工具栏等）
  cloud: Cloud,
  plug: Plug,
  pen: PenLine,
  trash: Trash2,
  globe: Globe,
  package: Package,
  key: Key,
  lock: Lock,
  clipboard: Clipboard,
  image: Image,
  sparkles: Sparkles,
  eraser: Eraser,
  'folder-plus': FolderPlus,
  pencil: Pencil,
  heart: Heart,
  'arrow-right': ArrowRight,
  'file-archive': FileArchive,
  'file-code': FileCode,
  'file-image': FileImage,
  'file-question': FileQuestionMark,
  'file-spreadsheet': FileSpreadsheet,
  'file-type': FileType,
  presentation: Presentation,
  // 文件树文件类型 / 三层【节点】图标（FolderTree 表示结构节点目录）
  'file-audio': FileAudio,
  'file-json': FileJson,
  'file-video': FileVideo,
  'file-pen': FilePen,
  'folder-tree': FolderTree,
  hash: Hash,
  todos: ListChecks,
  bell: Bell,
  alarm: AlarmClock,
};

export function Icon({
  name,
  size = 16,
  fill = false,
}: {
  name: string;
  size?: number;
  fill?: boolean;
}) {
  const Cmp = ICONS[name];
  if (!Cmp) return null;
  return <Cmp size={size} strokeWidth={1.6} fill={fill ? 'currentColor' : 'none'} />;
}

export default Icon;
